// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	DialogActions: {
		/**
		 * O​K
		 */
		Ok: string
		/**
		 * C​A​N​C​E​L
		 */
		Cancel: string
		/**
		 * Y​E​S
		 */
		Yes: string
		/**
		 * N​O
		 */
		No: string
		/**
		 * A​L​L​O​W
		 */
		Allow: string
		/**
		 * R​E​J​E​C​T
		 */
		Reject: string
	}
	Home: {
		/**
		 * D​o​m​a​i​n
		 */
		Domain: string
		/**
		 * D​e​v​i​c​e​I​D
		 */
		DeviceID: string
		/**
		 * R​e​m​o​t​e​ ​D​e​v​i​c​e​ ​I​D
		 */
		RemoteDeviceID: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		Password: string
		/**
		 * C​o​n​n​e​c​t
		 */
		Connect: string
		/**
		 * D​e​s​k​t​o​p
		 */
		Desktop: string
		/**
		 * F​i​l​e​s
		 */
		Files: string
		/**
		 * E​d​i​t​ ​P​a​s​s​w​o​r​d
		 */
		EditPasswordTooltip: string
		/**
		 * C​l​i​c​k​ ​t​o​ ​s​h​o​w​ ​p​l​a​i​n​ ​p​a​s​s​w​o​r​d
		 */
		PasswordVisibleTooltip: string
		/**
		 * H​i​d​e​ ​p​a​s​s​w​o​r​d​ ​w​h​e​n​ ​m​o​u​s​e​ ​l​e​a​v​e
		 */
		PasswordInvisibleTooltip: string
		/**
		 * C​a​n​c​e​l
		 */
		EditPasswordCancelTooltip: string
		/**
		 * C​l​i​c​k​ ​t​o​ ​C​o​p​y
		 */
		ClickToCopyDeviceIDTooltip: string
		/**
		 * C​o​p​i​e​d
		 */
		ClickToCopyDeviceIDCopiedTooltip: string
		/**
		 * G​e​n​e​r​a​t​e​ ​R​a​n​d​o​m​ ​P​a​s​s​w​o​r​d
		 */
		GenerateRandomPasswordTooltip: string
	}
	LAN: {
		/**
		 * H​o​s​t​n​a​m​e​ ​o​r​ ​I​P
		 */
		HostnameOrIP: string
		/**
		 * D​i​s​c​o​v​e​r​a​b​l​e
		 */
		Discoverable: string
	}
	Settings: {
		Appearance: {
			/**
			 * A​p​p​e​a​r​a​n​c​e
			 */
			Title: string
			/**
			 * T​h​e​m​e
			 */
			Theme: string
			/**
			 * L​i​g​h​t
			 */
			Light: string
			/**
			 * D​a​r​k
			 */
			Dark: string
			/**
			 * A​u​t​o
			 */
			Auto: string
		}
	}
	Dialogs: {
		About: {
			/**
			 * C​o​p​y
			 */
			Copy: string
		}
		VisitPrepare: {
			/**
			 * P​l​e​a​s​e​ ​i​n​p​u​t​ ​t​h​i​s​ ​d​e​v​i​c​e​'​s​ ​p​a​s​s​w​o​r​d
			 */
			Content: string
		}
		LANConnect: {
			/**
			 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​h​i​s​ ​d​e​v​i​c​e​?
			 */
			Content: string
		}
		SelectLanguage: {
			/**
			 * S​e​l​e​c​t​ ​L​a​n​g​u​a​g​e
			 */
			Title: string
		}
	}
}

export type TranslationFunctions = {
	DialogActions: {
		/**
		 * OK
		 */
		Ok: () => LocalizedString
		/**
		 * CANCEL
		 */
		Cancel: () => LocalizedString
		/**
		 * YES
		 */
		Yes: () => LocalizedString
		/**
		 * NO
		 */
		No: () => LocalizedString
		/**
		 * ALLOW
		 */
		Allow: () => LocalizedString
		/**
		 * REJECT
		 */
		Reject: () => LocalizedString
	}
	Home: {
		/**
		 * Domain
		 */
		Domain: () => LocalizedString
		/**
		 * DeviceID
		 */
		DeviceID: () => LocalizedString
		/**
		 * Remote Device ID
		 */
		RemoteDeviceID: () => LocalizedString
		/**
		 * Password
		 */
		Password: () => LocalizedString
		/**
		 * Connect
		 */
		Connect: () => LocalizedString
		/**
		 * Desktop
		 */
		Desktop: () => LocalizedString
		/**
		 * Files
		 */
		Files: () => LocalizedString
		/**
		 * Edit Password
		 */
		EditPasswordTooltip: () => LocalizedString
		/**
		 * Click to show plain password
		 */
		PasswordVisibleTooltip: () => LocalizedString
		/**
		 * Hide password when mouse leave
		 */
		PasswordInvisibleTooltip: () => LocalizedString
		/**
		 * Cancel
		 */
		EditPasswordCancelTooltip: () => LocalizedString
		/**
		 * Click to Copy
		 */
		ClickToCopyDeviceIDTooltip: () => LocalizedString
		/**
		 * Copied
		 */
		ClickToCopyDeviceIDCopiedTooltip: () => LocalizedString
		/**
		 * Generate Random Password
		 */
		GenerateRandomPasswordTooltip: () => LocalizedString
	}
	LAN: {
		/**
		 * Hostname or IP
		 */
		HostnameOrIP: () => LocalizedString
		/**
		 * Discoverable
		 */
		Discoverable: () => LocalizedString
	}
	Settings: {
		Appearance: {
			/**
			 * Appearance
			 */
			Title: () => LocalizedString
			/**
			 * Theme
			 */
			Theme: () => LocalizedString
			/**
			 * Light
			 */
			Light: () => LocalizedString
			/**
			 * Dark
			 */
			Dark: () => LocalizedString
			/**
			 * Auto
			 */
			Auto: () => LocalizedString
		}
	}
	Dialogs: {
		About: {
			/**
			 * Copy
			 */
			Copy: () => LocalizedString
		}
		VisitPrepare: {
			/**
			 * Please input this device's password
			 */
			Content: () => LocalizedString
		}
		LANConnect: {
			/**
			 * Do you want to connect this device?
			 */
			Content: () => LocalizedString
		}
		SelectLanguage: {
			/**
			 * Select Language
			 */
			Title: () => LocalizedString
		}
	}
}

export type Formatters = {}
