// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	DialogActions: {
		/**
		 * O​K
		 */
		Ok: string
		/**
		 * C​A​N​C​E​L
		 */
		Cancel: string
		/**
		 * Y​E​S
		 */
		Yes: string
		/**
		 * N​O
		 */
		No: string
		/**
		 * A​L​L​O​W
		 */
		Allow: string
		/**
		 * R​E​J​E​C​T
		 */
		Reject: string
	}
	Home: {
		/**
		 * D​o​m​a​i​n
		 */
		Domain: string
		/**
		 * D​e​v​i​c​e​I​D
		 */
		DeviceID: string
		/**
		 * R​e​m​o​t​e​ ​D​e​v​i​c​e​ ​I​D
		 */
		RemoteDeviceID: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		Password: string
		/**
		 * C​o​n​n​e​c​t
		 */
		Connect: string
		/**
		 * D​e​s​k​t​o​p
		 */
		Desktop: string
		/**
		 * F​i​l​e​s
		 */
		Files: string
		/**
		 * E​d​i​t​ ​P​a​s​s​w​o​r​d
		 */
		EditPasswordTooltip: string
		/**
		 * C​l​i​c​k​ ​t​o​ ​s​h​o​w​ ​p​l​a​i​n​ ​p​a​s​s​w​o​r​d
		 */
		PasswordVisibleTooltip: string
		/**
		 * H​i​d​e​ ​p​a​s​s​w​o​r​d​ ​w​h​e​n​ ​m​o​u​s​e​ ​l​e​a​v​e
		 */
		PasswordInvisibleTooltip: string
		/**
		 * C​a​n​c​e​l
		 */
		EditPasswordCancelTooltip: string
		/**
		 * C​l​i​c​k​ ​t​o​ ​C​o​p​y
		 */
		ClickToCopyDeviceIDTooltip: string
		/**
		 * C​o​p​i​e​d
		 */
		ClickToCopyDeviceIDCopiedTooltip: string
		/**
		 * G​e​n​e​r​a​t​e​ ​R​a​n​d​o​m​ ​P​a​s​s​w​o​r​d
		 */
		GenerateRandomPasswordTooltip: string
		/**
		 * D​o​m​a​i​n​ ​A​c​t​i​o​n​s
		 */
		DomainActions: string
		/**
		 * E​d​i​t
		 */
		DomainActionsEdit: string
		/**
		 * S​e​l​e​c​t​ ​P​r​i​m​a​r​y​ ​D​o​m​a​i​n
		 */
		SelectPrimaryDomain: string
	}
	LAN: {
		/**
		 * S​e​a​r​c​h​ ​H​o​s​t​n​a​m​e​ ​o​r​ ​I​P​ ​(​C​a​s​e​ ​S​e​n​s​i​t​i​v​e​)
		 */
		HostnameOrIP: string
		/**
		 * D​i​s​c​o​v​e​r​a​b​l​e
		 */
		Discoverable: string
	}
	Settings: {
		Appearance: {
			/**
			 * A​p​p​e​a​r​a​n​c​e
			 */
			Title: string
			/**
			 * T​h​e​m​e
			 */
			Theme: string
			/**
			 * L​i​g​h​t
			 */
			Light: string
			/**
			 * D​a​r​k
			 */
			Dark: string
			/**
			 * A​u​t​o
			 */
			Auto: string
		}
	}
	Dialogs: {
		About: {
			/**
			 * C​o​p​y
			 */
			Copy: string
			/**
			 * V​e​r​s​i​o​n
			 */
			Version: string
		}
		VisitPrepare: {
			/**
			 * P​l​e​a​s​e​ ​i​n​p​u​t​ ​t​h​i​s​ ​d​e​v​i​c​e​'​s​ ​p​a​s​s​w​o​r​d
			 */
			Content: string
		}
		LANConnect: {
			/**
			 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​h​i​s​ ​d​e​v​i​c​e​?
			 */
			Content: string
		}
		SelectLanguage: {
			/**
			 * S​e​l​e​c​t​ ​L​a​n​g​u​a​g​e
			 */
			Title: string
		}
		DomainList: {
			/**
			 * C​u​r​r​e​n​t​:
			 */
			Current: string
			Tooltips: {
				/**
				 * A​d​d​ ​n​e​w​ ​d​o​m​a​i​n
				 */
				Add: string
				/**
				 * S​e​t​ ​a​s​ ​p​r​i​m​a​r​y​ ​d​o​m​a​i​n
				 */
				SetPrimary: string
				/**
				 * E​d​i​t
				 */
				Edit: string
				/**
				 * D​e​l​e​t​e
				 */
				Delete: string
			}
		}
		DomainEdit: {
			/**
			 * E​d​i​t​ ​D​o​m​a​i​n
			 */
			Title: string
			/**
			 * N​a​m​e
			 */
			Name: string
			/**
			 * D​e​v​i​c​e​ ​I​d
			 */
			DeviceId: string
			FingerPrint: {
				/**
				 * F​i​n​g​e​r​P​r​i​n​t
				 */
				Label: string
				/**
				 * F​i​n​g​e​r​ ​p​r​i​n​t​ ​i​s​ ​a​ ​r​a​n​d​o​m​ ​s​t​r​i​n​g​ ​g​e​n​e​r​a​t​e​d​ ​a​t​ ​l​o​c​a​l​ ​o​n​c​e​ ​y​o​u​ ​c​o​n​n​e​c​t​e​d​ ​t​o​ ​a​ ​n​e​w​ ​d​o​m​a​i​n​.​ ​I​t​ ​i​s​ ​u​s​e​d​ ​t​o​ ​p​r​o​v​e​ ​y​o​u​r​ ​d​e​v​i​c​e​ ​h​a​s​ ​a​u​t​h​o​r​i​t​y​ ​t​o​ ​h​o​l​d​ ​a​ ​D​e​v​i​c​e​ ​I​d​ ​t​h​a​t​ ​D​o​m​a​i​n​ ​a​l​l​o​c​a​t​e​d​ ​f​o​r​ ​y​o​u​ ​f​o​r​ ​a​ ​w​h​i​l​e​ ​a​n​d​ ​i​t​ ​c​a​n​'​t​ ​b​e​ ​u​s​e​d​ ​t​o​ ​t​r​a​c​k​ ​y​o​u​r​ ​d​e​v​i​c​e​.
				 */
				Tooltip: string
			}
			/**
			 * R​e​m​a​r​k​s
			 */
			Remarks: string
			/**
			 * D​e​l​e​t​e
			 */
			Delete: string
			/**
			 * E​d​i​t
			 */
			Edit: string
		}
		DomainAdd: {
			/**
			 * A​d​d​ ​D​o​m​a​i​n
			 */
			Title: string
			/**
			 * D​o​m​a​i​n​ ​A​d​d​r​e​s​s​ ​(​I​P​:​P​o​r​t​ ​o​r​ ​U​R​L​)
			 */
			AddressInputPlaceHolder: string
			/**
			 * R​e​m​a​r​k​s
			 */
			RemarksInputPlaceHolder: string
		}
		DomainSwitch: {
			/**
			 * S​e​t​ ​P​r​i​m​a​r​y​ ​D​o​m​a​i​n
			 */
			Title: string
			/**
			 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​s​e​t
			 */
			ContentPrefix: string
			/**
			 * a​s​ ​p​r​i​m​a​r​y​ ​d​o​m​a​i​n​?
			 */
			ContentSuffix: string
		}
		DomainDelete: {
			/**
			 * D​e​l​e​t​e​ ​D​o​m​a​i​n
			 */
			Title: string
			/**
			 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​d​o​m​a​i​n
			 */
			ContentPrefix: string
			/**
			 * ?​ ​O​n​c​e​ ​y​o​u​ ​d​e​l​e​t​e​ ​i​t​ ​a​n​d​ ​y​o​u​ ​c​a​n​'​t​ ​r​e​c​o​v​e​r​y​!
			 */
			ContentSuffix: string
		}
	}
}

export type TranslationFunctions = {
	DialogActions: {
		/**
		 * OK
		 */
		Ok: () => LocalizedString
		/**
		 * CANCEL
		 */
		Cancel: () => LocalizedString
		/**
		 * YES
		 */
		Yes: () => LocalizedString
		/**
		 * NO
		 */
		No: () => LocalizedString
		/**
		 * ALLOW
		 */
		Allow: () => LocalizedString
		/**
		 * REJECT
		 */
		Reject: () => LocalizedString
	}
	Home: {
		/**
		 * Domain
		 */
		Domain: () => LocalizedString
		/**
		 * DeviceID
		 */
		DeviceID: () => LocalizedString
		/**
		 * Remote Device ID
		 */
		RemoteDeviceID: () => LocalizedString
		/**
		 * Password
		 */
		Password: () => LocalizedString
		/**
		 * Connect
		 */
		Connect: () => LocalizedString
		/**
		 * Desktop
		 */
		Desktop: () => LocalizedString
		/**
		 * Files
		 */
		Files: () => LocalizedString
		/**
		 * Edit Password
		 */
		EditPasswordTooltip: () => LocalizedString
		/**
		 * Click to show plain password
		 */
		PasswordVisibleTooltip: () => LocalizedString
		/**
		 * Hide password when mouse leave
		 */
		PasswordInvisibleTooltip: () => LocalizedString
		/**
		 * Cancel
		 */
		EditPasswordCancelTooltip: () => LocalizedString
		/**
		 * Click to Copy
		 */
		ClickToCopyDeviceIDTooltip: () => LocalizedString
		/**
		 * Copied
		 */
		ClickToCopyDeviceIDCopiedTooltip: () => LocalizedString
		/**
		 * Generate Random Password
		 */
		GenerateRandomPasswordTooltip: () => LocalizedString
		/**
		 * Domain Actions
		 */
		DomainActions: () => LocalizedString
		/**
		 * Edit
		 */
		DomainActionsEdit: () => LocalizedString
		/**
		 * Select Primary Domain
		 */
		SelectPrimaryDomain: () => LocalizedString
	}
	LAN: {
		/**
		 * Search Hostname or IP (Case Sensitive)
		 */
		HostnameOrIP: () => LocalizedString
		/**
		 * Discoverable
		 */
		Discoverable: () => LocalizedString
	}
	Settings: {
		Appearance: {
			/**
			 * Appearance
			 */
			Title: () => LocalizedString
			/**
			 * Theme
			 */
			Theme: () => LocalizedString
			/**
			 * Light
			 */
			Light: () => LocalizedString
			/**
			 * Dark
			 */
			Dark: () => LocalizedString
			/**
			 * Auto
			 */
			Auto: () => LocalizedString
		}
	}
	Dialogs: {
		About: {
			/**
			 * Copy
			 */
			Copy: () => LocalizedString
			/**
			 * Version
			 */
			Version: () => LocalizedString
		}
		VisitPrepare: {
			/**
			 * Please input this device's password
			 */
			Content: () => LocalizedString
		}
		LANConnect: {
			/**
			 * Do you want to connect this device?
			 */
			Content: () => LocalizedString
		}
		SelectLanguage: {
			/**
			 * Select Language
			 */
			Title: () => LocalizedString
		}
		DomainList: {
			/**
			 * Current:
			 */
			Current: () => LocalizedString
			Tooltips: {
				/**
				 * Add new domain
				 */
				Add: () => LocalizedString
				/**
				 * Set as primary domain
				 */
				SetPrimary: () => LocalizedString
				/**
				 * Edit
				 */
				Edit: () => LocalizedString
				/**
				 * Delete
				 */
				Delete: () => LocalizedString
			}
		}
		DomainEdit: {
			/**
			 * Edit Domain
			 */
			Title: () => LocalizedString
			/**
			 * Name
			 */
			Name: () => LocalizedString
			/**
			 * Device Id
			 */
			DeviceId: () => LocalizedString
			FingerPrint: {
				/**
				 * FingerPrint
				 */
				Label: () => LocalizedString
				/**
				 * Finger print is a random string generated at local once you connected to a new domain. It is used to prove your device has authority to hold a Device Id that Domain allocated for you for a while and it can't be used to track your device.
				 */
				Tooltip: () => LocalizedString
			}
			/**
			 * Remarks
			 */
			Remarks: () => LocalizedString
			/**
			 * Delete
			 */
			Delete: () => LocalizedString
			/**
			 * Edit
			 */
			Edit: () => LocalizedString
		}
		DomainAdd: {
			/**
			 * Add Domain
			 */
			Title: () => LocalizedString
			/**
			 * Domain Address (IP:Port or URL)
			 */
			AddressInputPlaceHolder: () => LocalizedString
			/**
			 * Remarks
			 */
			RemarksInputPlaceHolder: () => LocalizedString
		}
		DomainSwitch: {
			/**
			 * Set Primary Domain
			 */
			Title: () => LocalizedString
			/**
			 * Do you want to set
			 */
			ContentPrefix: () => LocalizedString
			/**
			 * as primary domain?
			 */
			ContentSuffix: () => LocalizedString
		}
		DomainDelete: {
			/**
			 * Delete Domain
			 */
			Title: () => LocalizedString
			/**
			 * Do you want to delete domain
			 */
			ContentPrefix: () => LocalizedString
			/**
			 * ? Once you delete it and you can't recovery!
			 */
			ContentSuffix: () => LocalizedString
		}
	}
}

export type Formatters = {}
