import { Button, VerticalBox } from "std-widgets.slint";
import { TitleBar } from "titlebar/titlebar.slint";
import { Theme } from "global/theme.slint";
import {DevicePage} from "pages/device/page.slint";

export * from "global/global.slint";

export component App inherits Window {
    title: "MirrorX";
    width: 960px;
    height: 660px;
    no-frame: true;
    default-font-family: "Microsoft YaHei UI";
    background: Theme.palette.background-level1;

    VerticalLayout { 
        Rectangle {  
            height: 48px;

            titlebar := TitleBar {  }
        }

        Rectangle {
            background: Theme.palette.background-body;
            if titlebar.selected-tab == "devices" : DevicePage{}

            if titlebar.selected-tab != "devices" : Text {
                text: titlebar.selected-tab;
            }
        }
     }
}