blank_issues_enabled: true
contact_links:
  - name: Questions / Help
    url: https://github.com/MirrorX-Desktop/MirrorX/discussions
    about: If you have any questions or want help when use MirrorX, please go to Github Discussions.
