import { Event } from "../global/event.slint";
import { Theme } from "../global/theme.slint";

export component MinButton {
    private property <image> minImage: @image-url("../images/remove_FILL0_wght700_GRAD0_opsz48.svg");
    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            Image {
                width: 24px;
                height: 24px;
                colorize: area.has-hover? Theme.palette.text-primary: Theme.palette.neutral-plain-disabled-color;
                source: minImage;
                animate colorize{ 
                    duration: 150ms;
                easing: ease-in-out;
                }

                area := TouchArea {
                    clicked => { 
                        Event.min-button-clicked();
                    }
                    mouse-cursor: pointer;
                }
            }
        }
    }
}