import {Theme} from "../../global/theme.slint";
import { HorizontalBox, Button, LineEdit } from "std-widgets.slint";
import {ConnectGroup} from "connect_group.slint";

export component DevicePage {
    VerticalLayout { 
        Rectangle { 
            
        }

        Rectangle { 
            height: 72px;
            background: Theme.palette.background-level2;

            HorizontalLayout { 
                alignment: space-between;
                padding: 12px;

                VerticalLayout {
                    alignment: center;
                    HorizontalLayout {
                        spacing: 16px;

                        Image { 
                            width: 24px;
                            height: 24px;
                            source: Theme.palette.is-light ? @image-url("../../images/github-mark.svg") : @image-url("../../images/github-mark-white.svg");
                            
                            TouchArea { 
                                mouse-cursor: MouseCursor.pointer;
                                clicked => { 
                                    // open url
                                }
                            }
                        }

                        Image { 
                            width: 24px;
                            height: 24px;
                            source: @image-url("../../images/signal_wifi_4_bar_FILL0_wght400_GRAD0_opsz48.svg");
                            colorize: Theme.palette.text-primary;

                            TouchArea { 
                                mouse-cursor: MouseCursor.pointer;
                                clicked => { 
                                    // open url
                                }
                            }
                        }
                    }
                }
            
            
                VerticalLayout {
                    alignment: center;
                    
                    ConnectGroup {  }
                }
                
            }
        }
    }
}