import { Theme } from "../../global/theme.slint";
import { HorizontalBox, Button, LineEdit } from "std-widgets.slint";
import { ConnectGroup } from "connect_group.slint";
import { AccountButton } from "account_button.slint";
import { ConnectionStatus } from "connection_status.slint";
import { CentralContent } from "central_content.slint";

export component DevicePage {
    VerticalLayout { 
        Rectangle { 
            CentralContent {  }
        }

        Rectangle { 
            height: 72px;
            background: Theme.palette.background-level2;

            HorizontalLayout { 
                alignment: space-between;
                padding: 12px;

                VerticalLayout {
                    alignment: center;
                    HorizontalLayout {
                        alignment: start;
                        spacing: 16px;
                 
                        AccountButton {  }

                        ConnectionStatus {  }
                    }
                }
                

                VerticalLayout {
                    alignment: center;
                    
                    ConnectGroup {  }
                }
                
            }
        }
    }
}