[package]
name = "mirrorx_viewport"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
tokio = { version = "1.26.0", features = ["full"] }
