#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    non_snake_case
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

use crate::api::*;
use flutter_rust_bridge::*;

// Section: imports

use crate::service::flutter_command::FlutterCommand;

// Section: wire functions

#[no_mangle]
pub extern "C" fn wire_init(port_: i64, config_db_path: *mut wire_uint_8_list) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "init",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_config_db_path = config_db_path.wire2api();
            move |task_callback| init(api_config_db_path)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_init_flutter_command_stream_sink(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "init_flutter_command_stream_sink",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || move |task_callback| init_flutter_command_stream_sink(task_callback.stream_sink()),
    )
}

#[no_mangle]
pub extern "C" fn wire_read_device_id(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "read_device_id",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| read_device_id(),
    )
}

#[no_mangle]
pub extern "C" fn wire_read_device_password(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "read_device_password",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| read_device_password(),
    )
}

#[no_mangle]
pub extern "C" fn wire_save_device_password(port_: i64, device_password: *mut wire_uint_8_list) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "save_device_password",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_password = device_password.wire2api();
            move |task_callback| save_device_password(api_device_password)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_generate_random_device_password(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "generate_random_device_password",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| generate_random_device_password(),
    )
}

#[no_mangle]
pub extern "C" fn wire_device_goes_online(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "device_goes_online",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| device_goes_online(),
    )
}

#[no_mangle]
pub extern "C" fn wire_desktop_connect_offer(port_: i64, ask_device_id: *mut wire_uint_8_list) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "desktop_connect_offer",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_ask_device_id = ask_device_id.wire2api();
            move |task_callback| desktop_connect_offer(api_ask_device_id)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_desktop_connect_offer_auth_password(
    port_: i64,
    ask_device_id: *mut wire_uint_8_list,
    device_password: *mut wire_uint_8_list,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "desktop_connect_offer_auth_password",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_ask_device_id = ask_device_id.wire2api();
            let api_device_password = device_password.wire2api();
            move |task_callback| {
                desktop_connect_offer_auth_password(api_ask_device_id, api_device_password)
            }
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_desktop_connect_open_stream(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "desktop_connect_open_stream",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| desktop_connect_open_stream(),
    )
}

// Section: wire structs

#[repr(C)]
#[derive(Clone)]
pub struct wire_uint_8_list {
    ptr: *mut u8,
    len: i32,
}

// Section: wrapper structs

// Section: static checks

// Section: allocate functions

#[no_mangle]
pub extern "C" fn new_uint_8_list(len: i32) -> *mut wire_uint_8_list {
    let ans = wire_uint_8_list {
        ptr: support::new_leak_vec_ptr(Default::default(), len),
        len,
    };
    support::new_leak_box_ptr(ans)
}

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        if self.is_null() {
            None
        } else {
            Some(self.wire2api())
        }
    }
}

impl Wire2Api<String> for *mut wire_uint_8_list {
    fn wire2api(self) -> String {
        let vec: Vec<u8> = self.wire2api();
        String::from_utf8_lossy(&vec).into_owned()
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
    fn wire2api(self) -> Vec<u8> {
        unsafe {
            let wrap = support::box_from_leak_ptr(self);
            support::vec_from_leak_ptr(wrap.ptr, wrap.len)
        }
    }
}

// Section: impl NewWithNullPtr

pub trait NewWithNullPtr {
    fn new_with_null_ptr() -> Self;
}

impl<T> NewWithNullPtr for *mut T {
    fn new_with_null_ptr() -> Self {
        std::ptr::null_mut()
    }
}

// Section: impl IntoDart

impl support::IntoDart for FlutterCommand {
    fn into_dart(self) -> support::DartCObject {
        match self {
            Self::PopupDesktopConnectInputPasswordDialog => 0,
        }
        .into_dart()
    }
}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

// Section: sync execution mode utility

#[no_mangle]
pub extern "C" fn free_WireSyncReturnStruct(val: support::WireSyncReturnStruct) {
    unsafe {
        let _ = support::vec_from_leak_ptr(val.ptr, val.len);
    }
}
