// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh-Hans'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * D​o​m​a​i​n
	 */
	Domain: string
	/**
	 * C​o​n​n​e​c​t
	 */
	Connect: string
	/**
	 * L​A​N
	 */
	LAN: string
	/**
	 * H​i​s​t​o​r​y
	 */
	History: string
	Pages: {
		Connect: {
			/**
			 * D​e​v​i​c​e​I​D
			 */
			DeviceID: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			Password: string
			/**
			 * R​e​m​o​t​e​ ​D​e​v​i​c​e​ ​I​D
			 */
			RemoteDeviceIDPlaceHolder: string
			/**
			 * D​e​s​k​t​o​p
			 */
			Desktop: string
			/**
			 * F​i​l​e​s
			 */
			Files: string
			Tooltips: {
				/**
				 * E​d​i​t​ ​P​a​s​s​w​o​r​d
				 */
				EditPassword: string
				/**
				 * C​l​i​c​k​ ​t​o​ ​s​h​o​w​ ​p​l​a​i​n​ ​p​a​s​s​w​o​r​d
				 */
				PasswordVisible: string
				/**
				 * H​i​d​e​ ​p​a​s​s​w​o​r​d​ ​w​h​e​n​ ​m​o​u​s​e​ ​l​e​a​v​e
				 */
				PasswordInvisible: string
				/**
				 * C​a​n​c​e​l
				 */
				EditPasswordCancel: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Domain
	 */
	Domain: () => LocalizedString
	/**
	 * Connect
	 */
	Connect: () => LocalizedString
	/**
	 * LAN
	 */
	LAN: () => LocalizedString
	/**
	 * History
	 */
	History: () => LocalizedString
	Pages: {
		Connect: {
			/**
			 * DeviceID
			 */
			DeviceID: () => LocalizedString
			/**
			 * Password
			 */
			Password: () => LocalizedString
			/**
			 * Remote Device ID
			 */
			RemoteDeviceIDPlaceHolder: () => LocalizedString
			/**
			 * Desktop
			 */
			Desktop: () => LocalizedString
			/**
			 * Files
			 */
			Files: () => LocalizedString
			Tooltips: {
				/**
				 * Edit Password
				 */
				EditPassword: () => LocalizedString
				/**
				 * Click to show plain password
				 */
				PasswordVisible: () => LocalizedString
				/**
				 * Hide password when mouse leave
				 */
				PasswordInvisible: () => LocalizedString
				/**
				 * Cancel
				 */
				EditPasswordCancel: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
